name: Node.js CI

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: "Test/Compile"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - run: npm ci
            - run: if [ $(ls -1 src/js/*.ts 2>/dev/null |wc -l) -ne 0 ]; then npm run tsc; fi
            - run: npm run test:unit
